// This file is automatically generated. Do not edit it directly.
//
// ⚠️  SECURITY NOTE — read this before adding new imports of this file.
// This file was deliberately merged from two files that used to be split:
//   - client.ts         (public "anon" client — safe in the browser)
//   - client.server.ts  (admin client using the service_role key — NOT safe
//                         in the browser, since it bypasses Row Level
//                         Security entirely and can read/write ANY row)
// TanStack Start treats files named `*.server.ts` as server-only and strips
// them from the browser bundle automatically. Because this combined file is
// no longer named `*.server.ts`, that automatic protection no longer
// applies — nothing here does the stripping for you anymore.
// The service_role key itself is never hardcoded (it's only ever read from
// `process.env.SUPABASE_SERVICE_ROLE_KEY` at runtime, and only inside
// server code paths, never `import.meta.env`), so it can't be baked into
// the client bundle as a literal string. Even so: only import
// `supabaseAdmin` from server-only code (server functions, `.functions.ts`
// server handlers, etc.) — never from a route/component file that renders
// in the browser.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Fallback project values, used ONLY if the environment variables below
 * aren't set wherever this app is actually running.
 *
 * This is safe to hardcode: a "publishable" key (like an anon key) is
 * designed to be public — it ships inside every browser bundle anyway, and
 * it can't do anything that Row Level Security doesn't already allow. This
 * is NOT the service_role key, which stays secret and server-only, and has
 * no equivalent fallback below.
 *
 * Real deployments should still set SUPABASE_URL / SUPABASE_PUBLISHABLE_KEY
 * (and their VITE_-prefixed equivalents) as proper environment variables —
 * this fallback just stops a missing/mistyped env var on the host from
 * taking down every single page with a hard crash.
 */
const FALLBACK_SUPABASE_URL = "https://bcunytrpoodnvlktxrxj.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_wsZ14LFmFgTA0Ok9VEd3nA_vUEK4wIq";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// ---------------------------------------------------------------------------
// "Remember me" storage adapter.
//
// Previously the login form had a "Remember me" checkbox that was checked
// by default, sent to nowhere, and did nothing — the client was hardcoded
// to `localStorage`, so every session persisted across browser restarts
// regardless of the checkbox. This adapter makes it real: unchecking it
// keeps the session in `sessionStorage` (cleared when the browser/tab
// closes) instead of `localStorage` (persists indefinitely). The choice is
// recorded under REMEMBER_FLAG_KEY *before* sign-in writes its session
// token, so this adapter can route that write to the right place.
// ---------------------------------------------------------------------------

const REMEMBER_FLAG_KEY = "taripon-remember-me";

export function setRememberPreference(remember: boolean) {
  try {
    localStorage.setItem(REMEMBER_FLAG_KEY, remember ? "1" : "0");
  } catch {
    // Ignore — storage may be unavailable (private browsing, disabled, etc).
  }
}

function rememberPreference(): boolean {
  try {
    return localStorage.getItem(REMEMBER_FLAG_KEY) !== "0";
  } catch {
    return true;
  }
}

function createRememberAwareStorage(): Storage {
  return {
    getItem: (key: string) => {
      try {
        return sessionStorage.getItem(key) ?? localStorage.getItem(key);
      } catch {
        return null;
      }
    },
    setItem: (key: string, value: string) => {
      try {
        if (rememberPreference()) {
          localStorage.setItem(key, value);
          sessionStorage.removeItem(key);
        } else {
          sessionStorage.setItem(key, value);
          localStorage.removeItem(key);
        }
      } catch {
        // Ignore — falls back to an in-memory session for this tab only.
      }
    },
    removeItem: (key: string) => {
      try {
        localStorage.removeItem(key);
        sessionStorage.removeItem(key);
      } catch {
        // Ignore.
      }
    },
    // Unused by supabase-js but required to satisfy the Storage interface.
    key: () => null,
    length: 0,
    clear: () => {
      try {
        localStorage.clear();
        sessionStorage.clear();
      } catch {
        // Ignore.
      }
    },
  };
}

// ---------------------------------------------------------------------------
// Public client — safe to use anywhere, including browser code.
// ---------------------------------------------------------------------------

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering), then to the
  // known-public project values as a last resort so a missing host env var
  // degrades gracefully instead of crashing every route.
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || FALLBACK_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    FALLBACK_SUPABASE_PUBLISHABLE_KEY;

  if (SUPABASE_URL === FALLBACK_SUPABASE_URL) {
    console.warn(
      "[Supabase] SUPABASE_URL / VITE_SUPABASE_URL isn't set in this environment — " +
        "falling back to the built-in project URL. Set it as a real environment " +
        "variable on your host and rebuild to remove this warning.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? createRememberAwareStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

// ---------------------------------------------------------------------------
// Admin client — service_role key, bypasses Row Level Security entirely.
// SERVER-ONLY. Only import `supabaseAdmin` from server functions / server
// handlers. Never import it from a route component or anything that renders
// in the browser — doing so risks shipping this code path into the client
// bundle now that it's no longer isolated in its own `*.server.ts` file.
// ---------------------------------------------------------------------------

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS.
// SECURITY: only use this for trusted server-side operations, never expose
// to client code. Prefer a dynamic import from inside server handlers, e.g.:
//   const { supabaseAdmin } = await import("@/integrations/supabase/client");
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
